version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_hoolhoja
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ifto
      - POSTGRES_DB=hoolhoja
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local